### ISSUE TITLE
HTTPS - Site seguro Bloqueia requisição

### ISSUE THREAD

**Issue by edianogama** [PostmonAPI/postmon#104]
Recebo o seguinte erro no console {was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.postmon.com.br/v1/cep/71993-380'. This request has been blocked; the content must be served over HTTPS.}
Alguém sabe como resolver ?

**Comment by iurisilvio** [comment]
Precisamos suportar HTTPS. Sua melhor opção por enquanto é fazer um proxy pelo seu servidor para o postmon. 

Mas SSL é realmente necessário para o postmon.

**Comment by iurisilvio** [comment]
O bug deve ser o Chrome começando a rejeitar chamadas HTTP de uma página HTTPS.

Um caso de uso muito importante para o postmon é o preenchimento de endereço no checkout, que precisa ser seguro.

@aleborba vamos colocar SSL nisso?

**Comment by aleborba** [comment]
Boa pergunta @iurisilvio. 

Acho que este custo é um pouco alto. E teriamos que mudar de servidor para fazer isso (e ai entra um outro custo) :(

**Comment by iurisilvio** [comment]
Tem alguns certificados gratuitos para OSS ou com custo bem reduzido. Esse é fácil de resolver.

Quanto ao servidor, por que seria necessário mudar?

**Comment by aleborba** [comment]
Hoje ele ainda esta debaixo da estrutura do iMasters. Não sei se teriamos todo o acesso necessário para fazer a mudança, uma vez que eu não estou mais lá. :(

**Comment by iurisilvio** [comment]
Entendi. Parece que chamadas HTTPS não chegam no servidor do postmon. Falta liberar alguma regra. :(

**Comment by aleborba** [comment]
Sabe qual seria essa regra? Vc tem acesso ssh la, certo?

**Comment by iurisilvio** [comment]
Esquece, as requisições estão chegando na 443 sim. :) Mas o Apache só está na porta 80, então recebo connection refused.

Para monitorar os pacotes com tcpdump: `tcpdump port 443 and '(tcp-syn|tcp-ack)!=0'`

Então o que precisa é só conseguir um certificado e configurar o Apache. Vou começar com um certificado auto assinado pra ver se funciona.

Vou criar uma issue pra isso.

**Comment by aleborba** [comment]
+1

**Comment by alancasagrande** [comment]
+1

Dá uma olhada no https://www.namecheap.com 

Tem o PositiveSSL que é só $9

**Comment by iurisilvio** [comment]
Eu iniciei o processo com o GoDaddy que daria o certificado de graça para projetos OSS, mas me deixaram em alguma fila de aprovação. :/

No fim de semana eu pago o certificado se não tiver resolvido ainda.

**Comment by iurisilvio** [comment]
@edianogama finalizei hoje a instalação do SSL no Postmon. Só fazer os requests para o HTTPS que não deve mais ter problemas.

**Comment by cristofersousa** [comment]
Pessoas deu certo?

**Comment by iurisilvio** [comment]
@cristofersousa Está com dificuldades no HTTPS?

**Comment by cristofersousa** [comment]
@iurisilvio  desculpa deu certo aqui fiz um teste usando o CodePen e vi que ela estava acusando problemas por não possuir https mas aí acompanhando aqui a thread vi que foi implementado.  

Agora está tudo ok > https://codepen.io/cristofersousa/full/vZebRV/

Obrigado.
