### ISSUE TITLE
Cliente para DotNet

### ISSUE THREAD

**Issue by fmmsilva** [PostmonAPI/postmon#106]
Pessoal, se for do interesse de vocês, criei um cliente do postmon para .net e comecei com a implementação básica de consulta de endereço através do CEP

**Comment by giolvani** [comment]
+1

**Comment by fmmsilva** [comment]
Está aqui: https://github.com/fmmsilva/postmon.net

**Comment by iurisilvio** [comment]
Fiz um fork na organização do postmon, apenas para facilitar a busca de alguém que esteja procurando.

Obrigado!
