### ISSUE TITLE
Porque Rio Grande do Sul (*)?

### ISSUE THREAD

**Issue by PauloFerreira25** [PostmonAPI/postmon#112]
Ola,
O estado do Rio Grande do Sul esta com um (*), isso é normal?
http://api.postmon.com.br/v1/cep/90010-150?format=xml
Atenciosamente,
Paulo Ferreira

**Comment by aleborba** [comment]
Esse é um caracter que vem na importação da base do IBGE (provavelmente alguma observação que eles colocam internamente, não sei). 

@iurisilvio, talvez fazer um trim antes de importar?

**Comment by julioeiras** [comment]
Acabei de abrir um PR que corrige o problema na importação dos dados de estados
https://github.com/PostmonAPI/postmon/pull/117

**Comment by PauloFerreira25** [comment]
TY

**Comment by iurisilvio** [comment]
Corrigido pelo pull request do @jcemelanda, subido pra produção hoje.

http://api.postmon.com.br/v1/cep/90010-150

```
{
  "bairro": "Centro Histórico",
  "cidade": "Porto Alegre",
  "cep": "90010150",
  "logradouro": "Praça da Alfândega",
  "estado_info": {
    "area_km2": "281.731,445",
    "codigo_ibge": "43",
    "nome": "Rio Grande do Sul"
  },
  "cidade_info": {
    "area_km2": "496,682",
    "codigo_ibge": "4314902"
  },
  "estado": "RS"
}
```
