### ISSUE TITLE
Servidor Caiu?

### ISSUE THREAD

**Issue by rodrigodrds** [PostmonAPI/postmon#114]
Não estou conseguindo fazer as requisições

**Comment by danizord** [comment]
Aqui tb :sob:

**Comment by aleborba** [comment]
@iurisilvio Ta sabendo de algo?

**Comment by rodrigoratan** [comment]
aqui tb.. só o server de API

**Comment by fdc263** [comment]
alternativa: http://cep.desenvolvefacil.com.br/BuscarCep.php?cep=92200290&ret=json

**Comment by iurisilvio** [comment]
Tem alguns clientes abusados que estão causando DoS na aplicação. Já está de volta.

Quem está travando é o apache. Vou trocar ele pelo uwsgi, que deve aguentar o tranco.

Estou acompanhando o problema. Também tenho aplicações em produção usando ele.

**Comment by danizord** [comment]
Não rola colocar um rate limit?

**Comment by iurisilvio** [comment]
Sim, foi minha solução de hoje cedo. Limitei os requests no nginx, mas mesmo assim o apache continuou caindo.

Já estou rodando com uwsgi, acompanhando para ver se não dá nenhum outro problema.

**Comment by rodrigodrds** [comment]
Valeu obrigado pela rápida resposta

**Comment by iurisilvio** [comment]
Já fazem 4 dias que estamos rodando com uwsgi e limit_req no nginx, sem nenhum problema.

http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

A carga de requests continua no mesmo nível, mas não causa nenhum problema.
