### ISSUE TITLE
statusText:"error"

### ISSUE THREAD

**Issue by hebertreis** [PostmonAPI/postmon#116]
Varios CEPs conhecidos com erro, estamos fora do ar? por qual motivo?

**Comment by victormiguez** [comment]
Estou passando pelo mesmo problema, aparentemente está fora do ar mesmo.

**Comment by FelipeKoblinger** [comment]
Realmente, aqui está fora do ar também. Torcendo para voltar em breve :+1:

**Comment by hebertreis** [comment]
![captura de tela 2015-10-07 as 04 15 01 pm](https://cloud.githubusercontent.com/assets/1006809/10348313/aecf5b1e-6d0e-11e5-8876-884299b3d139.png)

**Comment by iurisilvio** [comment]
Não foi exatamente uma queda, mas afetou muitos requests. O problema foi nas chamadas para os correios.

![image](https://cloud.githubusercontent.com/assets/105852/10354605/efcd9850-6d37-11e5-8758-8eed8af618dc.png)

Ainda estou tentando entender se houve algum motivo pra isso ou se foi só os correios travando mesmo.
