### ISSUE TITLE
Erro 403 para consultas por script python.

### ISSUE THREAD

**Issue by ramiroluz** [PostmonAPI/postmon#121]
Estou tentando consultar um CEP usando o python3.4 e urllib, mas
recebo o código 403. 

O user agent da requisição é User-Agent:.Python-urllib/3.4

A mensagem que recebo é essa: 
The owner of this website (api.postmon.com.br) has banned your access based on your browser's signature (248f264890681d0c-ua48).

**Comment by iurisilvio** [comment]
Não existe nenhum bloqueio específico.

Pode ser algum bloqueio automático no cloudflare ou rate limit do nginx. 

Nunca vi isso. Vou tentar entender o problema.

**Comment by ramiroluz** [comment]
Beleza. Se precisar de ajuda é só avisar.

On Sat, Nov 21, 2015 at 10:33 PM, Iuri de Silvio <notifications@github.com>
wrote:

> Não existe nenhum bloqueio específico.
>
> Pode ser algum bloqueio automático no cloudflare ou rate limit do nginx.
>
> Nunca vi isso. Vou tentar entender o problema.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PostmonAPI/postmon/issues/121#issuecomment-158694168>.
>



-- 
--
-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by iurisilvio** [comment]
Parece ser um bloqueio do cloudflare.

https://support.cloudflare.com/hc/en-us/articles/200171806-Error-1010-The-owner-of-this-website-has-banned-your-access-based-on-your-browser-s-signature

Desabilitei o "Browser Integrity Check", que não faz sentido para uma API.

Pode testar se agora funciona?

**Comment by ramiroluz** [comment]
Beleza, funcionou. Obrigado.


On Sat, Nov 21, 2015 at 11:15 PM, Iuri de Silvio <notifications@github.com>
wrote:

> Parece ser um bloqueio do cloudflare.
>
>
> https://support.cloudflare.com/hc/en-us/articles/200171806-Error-1010-The-owner-of-this-website-has-banned-your-access-based-on-your-browser-s-signature
>
> Desabilitei o "Browser Integrity Check", que não faz sentido para uma API.
>
> Pode testar se agora funciona?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PostmonAPI/postmon/issues/121#issuecomment-158697512>.
>



-- 
--
-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by iurisilvio** [comment]
:+1:

Nunca tinha visto esse problema com o CloudFlare. Aposto que tenho outras APIs com o mesmo problema.
