### ISSUE TITLE
API fora do ar

### ISSUE THREAD

**Issue by diegoleme** [PostmonAPI/postmon#122]
Infelizmente a API do postmon está fora do ar :cry:

**Comment by danilogcarolino** [comment]
Está no ar sim, Diego.

**Comment by samuelsimoes** [comment]
Aqui parece caído também.

**Comment by diegoleme** [comment]
@danilogcarolino estou fazendo um GET para essa url: http://api.postmon.com.br/v1/cep/05834000
e recebo o seguinte erro: ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by MarcosArtigas** [comment]
Também estou obtendo o mesmo erro..

**Comment by MarcosArtigas** [comment]
@danilogcarolino Talvez seja o CloudFlare bloqueando nossas requisições.

**Comment by danilogcarolino** [comment]
Então, na verdade agora que eu percebi que está dando erro para ~alguns~ CEP's. Reproduziu o problema aqui com alguns ceps de SP capital, mas outros funcionaram. Por exemplo: http://api.postmon.com.br/v1/cep/13502850

**Comment by rougeth** [comment]
@danilogcarolino esse link não está funcionando aqui e não estou conseguindo consultar nenhum cep.

**Comment by MarcosArtigas** [comment]
Mesmo através do site  http://postmon.com.br/ quando eu uso o "Exemplo de busca de CEP" ele retorna o seguinte conteúdo 

{"readyState":4,"responseText":"","status":200,"statusText":"OK"}

**Comment by hoomersinpsom** [comment]
Aqui também mesmo problema o/ testei no down for everyone lá também http://downforeveryoneorjustme.com/http://api.postmon.com.br

**Comment by IuryAlves** [comment]
Mesmo problema aqui.

**Comment by iurisilvio** [comment]
Resolvido. Um HD secundário lotou e não recebi nenhum aviso. :/

**Comment by iurisilvio** [comment]
Os requests que batiam no servidor, falhavam. Como o CloudFlare faz cache dos resultados (1d), no início vários resultados ainda funcionavam normalmente.

**Comment by diegoleme** [comment]
:smiley: :smiley: :smiley:

**Comment by MarcosArtigas** [comment]
Obrigado
Em 07/01/2016 23:04, "Diego Leme" <notifications@github.com> escreveu:

**Comment by IuryAlves** [comment]
Ae o/

**Comment by rougeth** [comment]
vlw @iurisilvio! \o/
