### ISSUE TITLE
api.postmon.com.br 500 Internal Server Error

### ISSUE THREAD

**Issue by arthurbarros** [PostmonAPI/postmon#125]
Ao tentar acessar a API de produção, e exibido um erro 500.

`https://api.postmon.com.br/v1/cep/01448000`

> Error: 500 Internal Server Error
> 
> Sorry, the requested URL 'https://api.postmon.com.br/v1/cep/01448000' caused an error:
> 
> Internal Server Error

**Comment by iurisilvio** [comment]
Resolvido. O mongo falhou na madrugada. :/
