### ISSUE TITLE
CEP não encontrado

### ISSUE THREAD

**Issue by gusilveiramp** [PostmonAPI/postmon#126]
Olá pessoal, o CEP 14020-530 está retornando erro. Não traz o endereço.
Existe alguma maneira de eu atualizar a base?

**Comment by iurisilvio** [comment]
Relacionado com #125.

Não é culpa de base desatualizada. O mongo que estava falhando em alguns casos. Resolvido.

**Comment by gusilveiramp** [comment]
Entendo... e tem como corrigir?

**Comment by iurisilvio** [comment]
Já está corrigido.

http://api.postmon.com.br/cep/14020-530

**Comment by iurisilvio** [comment]
Ou tem algum problema no resultado também? :)

**Comment by gusilveiramp** [comment]
Opa, que bom Iuri! Te agradeço imensamente, amigo. Tanto pelas respostas, quanto pela eficiência na resolução do problema. Me ajudou demais e com certeza a muitos outros também. Parabéns a você e sua equipe pelo trabalho que fazem. Grande abraço!
