### ISSUE TITLE
API está fora do ar

### ISSUE THREAD

**Issue by lelis718** [PostmonAPI/postmon#127]
A api não está funcionando mais

**Comment by guilhermehbueno** [comment]
+ 1

Estou tentando encontrar o seguinte CEP: http://api.postmon.com.br/v1/cep/94901-000
O status code retornado é: "404 CEP 94901000 nao encontrado".

Para outras consultas que eu já estava realizando ele funciona, talvez por causa de cache:

http://api.postmon.com.br/v1/cep/13076416

**Comment by dntxos** [comment]
Também não estou conseguindo realizar nenhuma consulta.

**Comment by iurisilvio** [comment]
Esqueci de responder, mas já está de volta faz tempo.

**Comment by dntxos** [comment]
Brigadis

**Comment by iurisilvio** [comment]
FYI, hoje eu implementei uma rota de health check. Para facilitar o meu monitoramento e também para ter uma forma fácil de qualquer um reconhecer problemas que estiverem acontecendo.

Se esse endpoint não responder ou responder com qualquer coisa que não seja HTTP 200, tem problema.

http://api.postmon.com.br/__health__
https://pypi.python.org/pypi/bottle-healthcheck
