### ISSUE TITLE
Cep 70373510 não retorna estado_info nem cidade_info

### ISSUE THREAD

**Issue by cguilhermef** [PostmonAPI/postmon#129]
Fazendo uma consulta pelo cep 70373510, as propriedades estado_info e cidade_info não estão presentes no retorno - e consequentemente todas as informações subsequentes.

**Comment by iurisilvio** [comment]
O DF não estava sendo carregado corretamente no `IbgeTracker` (105068ab22157a2e689b7deed4b7ca11550a927), desde a implementação inicial (@samuelgrigolato).

Corrigido com 1a1ea0d04c23dd763dd9d6a4db01556db70fa792.

Estou rodando novamente o tracker para já atualizar.

**Comment by cguilhermef** [comment]
Nice!! Muito obrigado

**Comment by cguilhermef** [comment]
Pela api, ainda não estão no retorno as propriedades mencionadas.

**Comment by iurisilvio** [comment]
O cache no CloudFlare mantém os resultados por 1 mês. Por isso não tinha atualizado. Dei uma limpada no cache, agora foi.

http://api.postmon.com.br/v1/cep/70373510

Esse cache longo faz sentido, já que dados de CEP não são atualizadas com frequência e na aplicação a gente já faz cache do resultado por mais tempo que isso.

**Comment by cguilhermef** [comment]
Entendo.

Bom, atualizei aqui e o estado_info apareceu. Só o cidade_info ainda não. Não sei se por conta de ser DF tem alguma diferença

**Comment by iurisilvio** [comment]
Não deveria ter diferença. Vou investigar.

**Comment by iurisilvio** [comment]
Realmente tinha um bug que potencialmente afetaria todos os resultados. O IBGE mudou todos os resultados para uppercase, aí não estava associando direito. Afetou apenas Brasília, porque as outras cidades já existiam na base. Se algum dia limpasse a base, ia aparecer o erro em tudo.

Corrigido em 96f06b37cfcf1477f29d3beeee45b6c9bd6d85ff. Já está em produção.
