### ISSUE TITLE
Alguns CEPs não estão funcionando

### ISSUE THREAD

**Issue by edwardknak** [PostmonAPI/postmon#130]
48609-190
95560-970

**Comment by iurisilvio** [comment]
A página dos Correios que o Postmon usa está falhando. Não sei se tem relação. Assim que voltar, investigo melhor.

http://m.correios.com.br/movel/buscaCep.do

```
0 javax.resource.resourceexception: ij000453: unable to get managed connection for java:/jdbc/dnecds 
```

**Comment by iurisilvio** [comment]
O site dos correios voltou a funcionar e esses CEPs também.

Mas sua issue foi muito útil. Eu implementei correndo um scraper para o site normal dos Correios (e0b154ff33c1a72663231ad3686b7aae76f585a0).

Vou agora criar issues para validar, testar e fazer switch automático entre os sites.
