### ISSUE TITLE
Erro 502 em alguns servidores

### ISSUE THREAD

**Issue by samuelsimoes** [PostmonAPI/postmon#133]
Olá pessoal,

No momento em que escrevo essa issue estou com um problema onde alguns servidores meus estão recebendo erro 502 (com layout do CloudFlare) na requisição de CEP, porém requisição ao `api.postmon.com/__health__` ocorre normalmente.

Vocês sabem o que pode estar acontecendo?

**Comment by rturk** [comment]
@samuelsimoes também estou com este erro. 

No meu caso o servidor rodo na AWS, mas somente faço 10-15 consultas dia!

    <span class="cf-footer-item">CloudFlare Ray ID: <strong>2acc157452df2474</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: </span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>

**Comment by rturk** [comment]
Parece ser um filtro anti-span muito agressivo do www.cloudflare.com

**Comment by rturk** [comment]
@iurisilvio você pode ajudar? Parece ser um filtro bem agressivo do CDN. Hoje fiz 12 consultas e fui bloqueado

**Comment by iurisilvio** [comment]
Isso não é filtro do cloudflare. 502 é erro de aplicação mesmo. O mongodb começou a consumir muita memória e aí deu uns timeouts.

Já deve estar normalizado. Continuarei monitorando pra ver se não volta a dar o mesmo problema.

**Comment by rturk** [comment]
@iurisilvio Estou curioso porque o MongoDB crashed. Com um CDN na frente o MongoDB deveria ter poucas consultas por segundo. Ou estou errado?

**Comment by iurisilvio** [comment]
@rturk Sim, você está certo. Com CloudFlare e nginx fazendo cache na frente, a quantidade de requests que bate na aplicação é pequena.

Quando alguma coisa assim dá errada, é um conjunto de fatores. Meu primeiro passo foi reiniciar o mongodb e isso resolveu.

Agora, olhando um pouco melhor, o mongodb caiu porque o uwsgi estava mantendo processos zumbis rodando, consumindo toda memória. Acho que relacionado com https://bugs.launchpad.net/ubuntu/+source/uwsgi/+bug/1131314.

Matei os processos zumbis e atualizei o uwsgi para evitar que isso aconteça de novo.

**Comment by samuelsimoes** [comment]
Aqui voltou ao normal. Muito obrigado pela atenção, @iurisilvio.

**Comment by rturk** [comment]
@iurisilvio eu sempre uso o uwsgi com `lazy-apps = true` me surpreende que isto não é a recomendação default. 

Diferente do NodeJS o python não consegue reconectar no MongoDB caso a conexão seja perdida, fica como você falou em **zumbi**. O `lazy-apps` força o uwsgi a matar o processo com problemas e cria um novo.

Isto é fundamental para aplicações em produção com o MongoDB rodando em replicaSet. Neste caso se os Mongos se reorganizam e elegem um novo master o usuário final não é prejudicado.

**Comment by iurisilvio** [comment]
Verdade. Atualmente eu uso `lazy-apps=true`, mas no postmon estava sem. Provavelmente a configuração dele foi antes de eu aprender isso. :/
