### ISSUE TITLE
Tracking ativo de pacotes

### ISSUE THREAD

**Issue by iurisilvio** [PostmonAPI/postmon#136]
Para quem faz tracking de encomendas, é necessário gastar recursos consultando várias vezes cada pacote. Isso pode ser centralizado no postmon.

```
POST /rastreio/<provider>/<track>
{
  "callback": "http://httpbin.org/post",
  "meuid": "42",
  "outro": "valor"
}
```

Com isso, o postmon fica consultando os pacotes periodicamente e avisa o `callback` quando tiver alterações. Todos os outros parâmetros definidos no POST serão enviados na chamada dos callbacks.

```
POST <callback>
{
  "input": {
    "callback": "http://httpbin.org/post",
    "meuid": "42",
    "outro": "valor"
  },
  "codigo": "PJ995358841BR",
  "servico": "ect",
  "historico": [
    ...
  ]
}
```
- `callback` é o melhor nome?
- Os dados adicionais no POST inicial devem ser limitados?
- Os dados adicionais devem ser retornados em um outro campo para evitar conflito?

Pontos ainda não tratados:
- Definição dinâmica de quando o pacote deve ser consultado novamente
- Parar de fazer consultas depois de entregue
- Distribuição das chamadas de callback
- Regras para retentativas de chamada do callback

**Comment by iurisilvio** [comment]
Implementação inicial na branch `track_ativo`. https://github.com/PostmonAPI/postmon/compare/track_ativo

**Comment by iurisilvio** [comment]
@aleborba @ihercowitz ou qualquer outro que usa o tracking de pacotes do postmon, quero comentários sobre a API.

**Comment by aleborba** [comment]
@iurisilvio eu gosto da implementação. minha pergunta é: isso nao sobrecarregaria o servidor? como controlar para pessoas nao usarem isso indiscriminadamente?

e no lugar de callback chamar de notification?

**Comment by iurisilvio** [comment]
Hoje já temos o abuso de alguns usuários. Minha ideia é que isso reduza a quantidade de requests de rastreio e dê maior controle sobre quando fazemos os requests para os Correios. Complica um pouco a infra, mas melhora a qualidade do sistema.

Estou tentando evitar a identificação para o uso básico do postmon, porque acho que vai contra a ideia da API aberta. Rate-limit por ip é suficiente por enquanto para manter o serviço estável. Vou trabalhar na ideia de identificação dos usuários para outras funcionalidades.

Sobre `notification`, pode ser melhor que `callback`, porque são várias chamadas, não apenas uma de callback.

**Comment by aleborba** [comment]
:+1:

**Comment by iurisilvio** [comment]
imagem para ilustrar o problema.

![image](https://cloud.githubusercontent.com/assets/105852/17839457/c9a7b9b2-67be-11e6-83cf-39d7786c9296.png)

Se eu puder distribuir uniformemente essa carga que acontece de hora em hora, já vale essa alteração.

**Comment by aleborba** [comment]
boa!

**Comment by iurisilvio** [comment]
Implementação inicial integrada e em produção. Faltam funcionalidades, mas o callback funciona.

Vou abrir issues para os próximos passos.
