### ISSUE TITLE
estado_info nulo 

### ISSUE THREAD

**Issue by andersonscherrrer** [PostmonAPI/postmon#140]
Ao efetuar a consulta:
http://api.postmon.com.br/v1/cep/85805140
A resposta obtida foi:
{
 "bairro": "Alto Alegre", 
 "cidade": "Cascavel", 
 "estado": "PR", 
 "logradouro": "Rua Gomercindo Pompeu da Silva", 
 "cep": "85805140"
}
A resposta esperada era:
estado_info e cidade_info

**Comment by iurisilvio** [comment]
Resolvido. Mesma coisa da #141.
