### ISSUE TITLE
Código do IBGE deixou de ser retornado

### ISSUE THREAD

**Issue by masimao** [PostmonAPI/postmon#141]
O código do IBGE deixou de ser retornado na resposta do Postmon, houve alguma alteração na estrutura do retorno? Alguns CEPs de exemplo:

58046-518
58070-450
58052-230
58108-502
53520-710

**Comment by iurisilvio** [comment]
Corrigido.

http://api.postmon.com.br/v1/cep/58046-518

Fiz algumas mudanças e faltou migrar esses dados.

**Comment by iurisilvio** [comment]
As mudanças foram de infra, não de código. O serviço agora está muito mais rápido e estável.

**Comment by masimao** [comment]
@iurisilvio Para os demais casos o problema persiste:

http://api.postmon.com.br/v1/cep/58051640
http://api.postmon.com.br/v1/cep/58070-450
http://api.postmon.com.br/v1/cep/58052-230
http://api.postmon.com.br/v1/cep/58108-502
http://api.postmon.com.br/v1/cep/53520-710

Existe uma maneira de vocês realizarem a correção para que a base fique conforme estava antes?

**Comment by iurisilvio** [comment]
Todas essas URLs já estão corrigidas. Você está acessando do navegador? Tem algum cache local provavelmente.
