### ISSUE TITLE
Rastreio de encomendas

### ISSUE THREAD

**Issue by juniorschroder** [PostmonAPI/postmon#142]
Incluir no response header do rastreio o atributo:

Access-Control-Allow-Origin:*

**Comment by iurisilvio** [comment]
Feito em 678e89d44d426067ebe7e5fa5f952314137b03c7.

Tentei usar o `bottle.hook("after_request")` mas ele não funciona como eu esperava. Alguma hora tento novametne, para evitar a duplicação de código.
