### ISSUE TITLE
cep não encontrado via api

### ISSUE THREAD

**Issue by eduardogsilva** [PostmonAPI/postmon#143]
Boa tarde, 

Não tenho certeza se realmente é um problema, mas por via das dúvidas resolvi reportar.
Detectei um cep que é encontrado no site dos correios mas não é retornado pela api do postmon: 
Retorno: {"readyState":4,"responseText":"","status":404,"statusText":"CEP 20510130 nao encontrado"}

Obrigado!

**Comment by iurisilvio** [comment]
Obrigado pelo report. É um problema sim, gerado pelo #138.

Resolvi para o CEP que você citou, deletando um registro do mongo.

Criei uma issue para tratar o problema corretamente. Se quiser acompanhar, veja #144.
