### ISSUE TITLE
Como é mantida a API REST?

### ISSUE THREAD

**Issue by rbrandino1** [PostmonAPI/postmon#148]
Pessoal, vi o projeto, e pretendo fazer uso da consulta via REST com AngularJS.

Minha dúvida é: 
Quem mantei o link funcionando? 
Como são mantidos os custos?

Pergunto isso, pois, gostaria de saber se corro muitos riscos da minha implementação baseada nessa consulta REST, deixar de funcionar tão logo, caso o link não esteja mais no ar.

Abraços

**Comment by iurisilvio** [comment]
A resposta mais correta para um projeto aberto desse tipo é que fazemos o possível para manter o Postmon rodando, mas se por acaso isso não acontecer mais, você pode fazer o deploy dele em uma infra sua e continuar usando.

Desde o início (dezembro/2012) conseguimos manter os servidores com patrocínio, nenhum custo para mim ou para qualquer desenvolvedor do projeto. Recebemos algumas doações (quero aumentar isso!) que garantem o pagamento do domínio (30/ano), o único gasto crítico do projeto.

Não posso dar muitos detalhes, mas o Postmon é crítico para mim em alguns projetos de longo prazo. Além disso, temos algumas empresas grandes usando ele e outras de amigos que já me ofereceram infra para ele.

São ~11 milhões de requests/mês, 75% respondido pelo CloudFlare (free). Estatísticas de respostas dadas pelo servidor podem ser vistas em http://stats.postmon.com.br. O monitoramento do Postmon e dos Correios é mostrado em http://status.postmon.com.br (do hund.io, de graça).

O código já é bem estável, às vezes faço alguma manutenção e tenho planos de criar algumas funcionalidades novas. Contribuições são sempre bem-vindas.

**Comment by iurisilvio** [comment]
Fechando a issue, mas fique a vontade para reabrir caso tenha mais alguma dúvida.
