### ISSUE TITLE
Tratamento de erros

### ISSUE THREAD

**Issue by edoura** [PostmonAPI/postmon#150]
Mensagens para tratamento de erros. Ao invés de receber um not found 404, ao digitar um cep inexistente

No Console:
![erro](https://cloud.githubusercontent.com/assets/943480/19532198/76bc3f78-9619-11e6-9659-d713d3d34b2f.png)

**Comment by duduribeiro** [comment]
IMHO o 404 not found é muito claro que o cep não foi encontrado.

**Comment by duduribeiro** [comment]
@edoura a mensagem já te diz que o seu cep não foi encontrado.

**Comment by aleborba** [comment]
Hey @edoura, é uma prática de rest usar os codigos do protocolo para os resultados. 

404 é not found e facilmente tratável. :)

De qualquer forma, obrigado pela sugestão. 

Fechando como Intended Behavior.

**Comment by iurisilvio** [comment]
:+1:

Os status são usados para dar essa informação.
