### ISSUE TITLE
Melhores práticas

### ISSUE THREAD

**Issue by brunomonteiro3** [PostmonAPI/postmon#151]
Olá, primeiramente muito obrigado por fornecer essa API, ela esta sendo muito útil e fácil de usar. No entanto, ainda tenho algumas dúvidas.

Qual é o melhor maneira para solicitar os dados? Posso fazer um AJAX via JS ou o request deve partir do servidor?

Existe algum limite de requests diárias? Se sim, quantas?

Obrigado!

**Comment by iurisilvio** [comment]
Faça direto pelo cliente, por AJAX. Isso simplifica sua infra, que é o objetivo do postmon. Diminui quantidade de requests no seu servidor, não precisa tratar possíveis timeouts e erros, etc.

O Postmon não tem limite diário. Tem alguns limites soft para evitar muitos requests simultâneos do mesmo IP (o que é outro motivo para direto pelo cliente), apenas para garantir a saúde dos servidores.

Hoje fazemos ~800k requests/dia e temos infra pra servir bem mais que isso sem dificuldade.

**Comment by brunomonteiro3** [comment]
Obrigado @iurisilvio.

**Comment by iurisilvio** [comment]
:+1:
