### ISSUE TITLE
API indisponível!

### ISSUE THREAD

**Issue by lhpalacio** [PostmonAPI/postmon#152]
A API está fora do ar!

**Comment by iurisilvio** [comment]
Corrigido já. Um servidor reiniciou e a aplicação não voltou por erro de configuração. Tratei a causa disso, não vai acontecer novamente.

O cache do nginx cria o diretório mas não cria subdiretórios. O cache do postmon estava em `/tmp/postmon/cache`, então falhou para iniciar o cache e o nginx não subiu. Mudei para `/tmp/postmon.cache` para tratar.
