### ISSUE TITLE
Informação

### ISSUE THREAD

**Issue by xereda** [PostmonAPI/postmon#155]
Olá,

Em qual VPS o serviço encontra-se hospedado atualmente? Qual a capacidade máxima de acessos simultâneos ao serviço?

Primeiramente faço essas questões, pois achei o ping de 13ms excelente e outra é que precisamos validar se é possível usá-lo em nosso serviço em produção.

Desde já agradeço o retorno.

**Comment by iurisilvio** [comment]
O servidor está hoje na AWS no Brasil (sa-east-1), por isso a latência é baixa. Além disso, tem o CloudFlare fazendo edge cache.

Temos capacidade para servir seus requests. Existe um soft limit de requisições por IP, apenas para manter a saúde dos servidores e evitar abusos, mas quando a resposta é do CloudFlare (maioria dos CEPs), essa limitação não existe.

Respondi essa e mais algumas dúvidas aqui: https://github.com/PostmonAPI/postmon/issues/148#issuecomment-242402557

Apenas para atualizar os números...

 * Estamos em ~29 milhões de requests/mês (requests aumentaram 2,6x em 6 meses).
 * CloudFlare serve 91% dos requests.
 * Paramos de atualizar o stats.postmon.com.br, porque a manutenção dele é complicada e o resultado vale muito pouco, porque conta apenas os hits no servidor (<10%).

Fechando a issue, mas fique a vontade para reabrir com mais dúvidas sobre isso.

**Comment by xereda** [comment]
Muito bom! Parabéns!
