### ISSUE TITLE
Pesquisa de código de rastreio retornando erro 404

### ISSUE THREAD

**Issue by aykou** [PostmonAPI/postmon#167]

**Comment by iurisilvio** [comment]
Você pode dar algum exemplo de código de rastreio?

404 é resposta esperada quando o pacote ainda não está registrado nos Correios. O http status deve ser `404 Pacote <track> nao encontrado`. https://github.com/PostmonAPI/postmon/blob/master/PostmonServer.py#L198

Os servidores não parecem estar com nenhum comportamento inesperado.
