### ISSUE TITLE
Link offline - http://api.postmon.com.br/v1/rastreio/ect/

### ISSUE THREAD

**Issue by peteraf** [PostmonAPI/postmon#168]
Testei o link:
http://api.postmon.com.br/v1/rastreio/ect/PL643007648BR
Entretanto  retorna: Não foi possível encontrar a página deste api.postmon.com.br / HTTP ERROR 404

O código de rastreio PL643007648BR é valido.

**Comment by rpedigoni** [comment]
Parece que o websro foi desligado, está redirecionando.

```
curl -v "http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_ITEMCODE=&P_LINGUA=001&P_TESTE=&P_TIPO=001&P_COD_UNI=XXX"
*   Trying 200.252.60.71...
* Connected to websro.correios.com.br (200.252.60.71) port 80 (#0)
> GET /sro_bin/txect01$.QueryList?P_ITEMCODE=&P_LINGUA=001&P_TESTE=&P_TIPO=001&P_COD_UNI=XXX HTTP/1.1
> Host: websro.correios.com.br
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Mon, 17 Apr 2017 13:03:43 GMT
< Server: Apache/1.3.41 (Unix) mod_perl/1.31
< Location: http://www2.correios.com.br/sistemas/rastreamento/
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=iso-8859-1
```

**Comment by iurisilvio** [comment]
Percebi que o `websro` estava caindo muito já há alguns dias, já estamos rodando com o `www2` (http://www2.correios.com.br/sistemas/rastreamento/). Não foi esse o problema.

Vi nos logs que realmente retornou 404 várias vezes para esse pacote, inclusive hoje. Quando eu testei a URL retornou corretamente.

Vou dar uma investigada para ver se foi um problema pontual. Esse endpoint não tem nenhum cache, todos os requests bateram na aplicação e ela retornou 404.

O motivo mais comum de retornar 404 é o pacote ainda não estar registrado nos Correios, mas esse aí é bem antigo. https://github.com/PostmonAPI/postmon/blob/master/PostmonServer.py#L192

Não tenho certeza se é o mesmo problema, mas #167 parece relacionado.

Logs. O último foi meu teste.

```
[15/Apr/2017:10:07:32 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[15/Apr/2017:10:11:16 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[15/Apr/2017:10:17:30 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[15/Apr/2017:15:24:59 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:01:47:40 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:20:23:49 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:21:07:38 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:22:54:15 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:22:57:49 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[16/Apr/2017:23:11:22 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[17/Apr/2017:00:01:16 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[17/Apr/2017:00:18:31 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[17/Apr/2017:09:26:07 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[17/Apr/2017:09:42:22 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 404 0
[17/Apr/2017:09:58:13 -0300] "GET /v1/rastreio/ect/PL643007648BR HTTP/1.1" 200 381
```

**Comment by rpedigoni** [comment]
Voltou!

**Comment by iurisilvio** [comment]
O `www2` está retornando 403 para vários requests de um dos servidores do Postmon, aparentemente o volume de requests do postmon começou a incomodar.

Isso é crítico. Possíveis soluções:

 * Proxy com ip rotativo
 * Mais servidores para distribuir os requests
 * Limitar requests de rastreio

**Comment by lhpalacio** [comment]
@iurisilvio Seria possivel/viável utilizar a API oficial como alternativa ao `www2` e o `websro`?

https://webservice.correios.com.br/service/rastro/Rastro.wsdl

**Comment by iurisilvio** [comment]
@lhpalacio para usar esse serviço precisa de um contrato com os Correios. Não sei se tem algum custo, mas acredito que sim. Não tenho certeza se isso elimina o risco de ser bloqueado por IP.

Uma opção é usar o contrato de quem usa o postmon. Isso aumenta um pouco o problema, depende de cadastrar cada usuário e manter usuário/senha de terceiros.

A solução escalável é limitar os requests e ter opção dedicada/paga para os maiores usuários. Quero no longo prazo fazer o postmon ser sustentável.

**Comment by lhpalacio** [comment]
@iurisilvio na verdade está é pública, apesar de pedir um usuário e senha não é atrelado ao contrato do cliente.

Nesse manual tem o usuário e senha:
https://www.correios.com.br/para-voce/correios-de-a-a-z/pdf/rastreamento-de-objetos/manual_rastreamentoobjetosws.pdf

Usuario: ECT
Senha: SRO

Eu tenho no meu sistema implementado o postmon e a API oficial, no entanto o padrão no meu sistema é o postmon, pois em todos os testes que fiz a oficial teve um desempenho bem inferior, alem de ser intermitente. Apesar disso acho que não devemos descartar como uma alternativa, até porque o correios já demonstrou uma vez que pretende descontinuar o `websro`.

**Comment by iurisilvio** [comment]
Já tinha visto o manual, mas não prestei atenção no usuário/senha. Vou implementar. Mesmo que seja mais lento, é bom ter como opção.

**Comment by rpedigoni** [comment]
@iurisilvio, @lhpalacio: criei uma lib que implementa o webservice SOAP, caso ajude:
https://github.com/rpedigoni/trackr

**Comment by lhpalacio** [comment]
Atualização do correios em relação ao `websro`.

http://www.correios.com.br/para-voce/avisos/atualizacao-do-sistema-de-rastreamento-de-objetos-sro/

ping: @iurisilvio

**Comment by iurisilvio** [comment]
@rpedigoni eu já tinha a implementação do SOAP no packtrack também usando o zeep. Poderia ter incluido o `trackr` como dependência do `packtrack`, mas preferi evitar mais um nível de dependência.

@lhpalacio realmente abandonaram o `websro`.

Ontem subi a implementação do SOAP, já está rodando. A performance desse service é muito melhor (~80ms, antes era ~1,5s), então o tempo de resposta do postmon melhorou muito. Estou testando aumentar um pouco o limite de requests concorrentes por IP (`limit_req_zone rate=5r/s`). :)

Ainda falta ter certeza que o service não bloqueia IP por volume de requests, mas pela performance deles, deve ter um limite muito mais alto.

**Comment by lhpalacio** [comment]
@iurisilvio Esse novo `websro` vai ser usado também?

Não consegui entender o porquê de mudar de GET para POST, teoricamente o `websro` servia para que os lojistas pudessem disponibilizar um link direto para o rastreio do objeto. Nesse novo formato parece que foi feito especialmente para ser usado pelo postmon. :confused:

**Comment by iurisilvio** [comment]
Também não entendi isso de tirar a opção do GET. Forçar os lojistas a integrarem é ruim. Achava que os Correios queriam exatamente o contrário, dar acesso aos lojistas e eliminar os robôs.

Como agora o tracking do postmon é apenas um wrapper da API dos Correios (SOAP -> json). Falta ainda documentação, mas é simples.

http://correios.postmon.com.br/webservice/buscaEventos/?objetos=PN876436923BR

Obedece a API dos Correios, então dá por exemplo pra fazer request de mais de um pacote `objetos=PN876436923BRPL657535905BR`.

Além disso, vou tentar cobrir esse buraco deixado pelos Correios para os lojistas. Comecei apenas copiando o websro (você pode só mudar a base da URL que funciona), mas pretendo fazer uma página de tracking de verdade.

http://correios.postmon.com.br/websro/?P_COD_UNI=PN876436923BR

**Comment by iurisilvio** [comment]
@lhpalacio respondendo a sua pergunta, o "novo websro" já está implementado no packtrack como `www2` (https://github.com/aleborba/packtrack/blob/master/packtrack/scraping.py#L43). O postmon tem a opção de usar ele, mas a performance dele foi sempre muito pior que do websro.

Estou acreditando que o SOAP vai ser sempre muito mais eficiente e provavelmente internamente o `www2` usa ele nos Correios, então se o service cai, o `www2` cai também. É o que tenho visto no monitoramento que faço deles. Então o `www2` não serve nem como fallback.

**Comment by lhpalacio** [comment]
@iurisilvio esse que você mandou o link parece acessar a versão completa do site, o novo é uma versão sem conteudo, talvez isso afete o desempenho.

Link do novo: http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm

Eu tenho uma péssima experiencia com essa API da ECT, desde que eu implementei as assinaturas dos métodos públicos já mudaram duas vezes sem avisar, apesar disso, acredito que eles estão esforçando em definir um padrão.

No caso de mudança nos métodos do webservice o `www2` deve ser o primeiro a receber as alterações para não parar de funcionar, ai sim serviria como fallback até que possamos implementar as mudanças. É só uma situação hipotética.

Acho uma boa ideia ter uma página de tracking, talvez possa até ser usada para monetizar o projeto.

**Comment by iurisilvio** [comment]
Realmente, o link é diferente. Nem tinha reparado. :)

Comecei a fazer alguns testes com esse link novo e a performance é horrível. Quando recebo resposta, são uns 2s, mas várias vezes demora uns 5s e dá erro. Como lojista, eu não usaria. Vou misturar todas essas opções para dar uma solução confiável.

A ideia da página de tracking é monetizar mesmo. Já estou pensando nisso há algum tempo.

![screencapture-file-home-iurisilvio-code-oss-correios-proxy-a-html-1493992383491](https://cloud.githubusercontent.com/assets/105852/25748454/75a91166-3181-11e7-9e28-de0100372ae0.png)

**Comment by iurisilvio** [comment]
Escrevi uma documentação básica com exemplos do que pode ser feito.

Vou fechar essa issue que já está resolvida e criar issues para os próximos passos no https://github.com/PostmonAPI/correios.postmon.com.br

**Comment by rafaelxavierborges** [comment]
> Também não entendi isso de tirar a opção do GET. Forçar os lojistas a integrarem é ruim. Achava que os Correios queriam exatamente o contrário, dar acesso aos lojistas e eliminar os robôs.
> 
> Como agora o tracking do postmon é apenas um wrapper da API dos Correios (SOAP -> json), isolei isso em um domínio. Falta ainda documentação, mas é simples.
> 
> http://correios.postmon.com.br/webservice/buscaEventos/?objetos=PN876436923BR
> 
> Obedece a API dos Correios, então dá por exemplo pra fazer request de mais de um pacote `objetos=PN876436923BRPL657535905BR`.
> 
> Além disso, vou tentar cobrir esse buraco deixado pelos Correios para os lojistas. Comecei apenas copiando o websro (você pode só mudar a base da URL que funciona), mas pretendo fazer uma página de tracking de verdade.
> 
> http://correios.postmon.com.br/websro/?P_COD_UNI=PN876436923BR

@iurisilvio Independente do código de rastreio o HTML resultante é sempre o mesmo, só muda a data/hora, o resto; tudo igual.
