### ISSUE TITLE
Busca por faixa de CEPs

### ISSUE THREAD

**Issue by aleborba** [PostmonAPI/postmon#17]
Buscar as informações de uma faixa de ceps

**Comment by rogeriolino** [comment]
Seria interessante se tivesse um retorno da faixa de CEP (inicial e final) por Estado e por Estado+Cidade.

O que os Correios disponibilizam nessa página:
http://www.buscacep.correios.com.br/sistemas/buscacep/BuscaFaixaCEP.cfm
