### ISSUE TITLE
API esta retornando somente a última situação da postagem.

### ISSUE THREAD

**Issue by peteraf** [PostmonAPI/postmon#171]
API esta retornando somente a última situação da postagem.

Exemplo: 
http://api.postmon.com.br/v1/rastreio/ect/PL643007648BR

Retorna somente que o objeto foi entregue, falta quando foi postado e passando por outras agencias, etc.

**Comment by iurisilvio** [comment]
A API dos Correios está retornando sem os detalhes.

http://correios.postmon.com.br/webservice/buscaEventos/?objetos=PN876436923BR

Ontem pela noite o webservice ficou fora do ar por algumas horas, provavelmente teve alguma alteração, mas não encontrei nenhuma documentação sobre isso. Vou esperar um pouco para ver se o webservice volta ao normal.

**Comment by leanfj** [comment]
Ola @iurisilvio Parece que o sistema do api.postmon ficou fora de vez.O correios.postmon ainda funciona mas com a limitação do ultimo endereço do objeto de postagem. Estou estudando a doc dos correios e a sua. Se eu puder contribuir com alguma coisa eu mando aqui para vocês

**Comment by iurisilvio** [comment]
Eu havia alterado o backend do Postmon para buscar direto no site dos Correios, mas isso não é mais possível, nosso volume de consultas vai em algum firewall deles bem rápido. Voltei agora para usar o serviço.

Os Correios estão fazendo alguma migração de infra-estrutura deles, por isso estão com tantos problemas. O webservice deles ficou fora do ar boa parte do dia ontem. Tá dificil depender deles.

https://status.postmon.com.br/778946668

**Comment by leanfj** [comment]
Ok @iurisilvio muito obrigado. Se eu conseguir mais alguma informação com meu estudos e pesquisas aqui eu retorno. Espero estar ajudando.

**Comment by iurisilvio** [comment]
Com certeza essas informações ajudam. Mandei email para o suporte dos Correios, mas ainda sem resposta.

Difícil dar uma solução porque o serviço que a gente depende que está respondendo errado.

Vou deixar essa issue aberta até entender porque o webservice mudou.

**Comment by iurisilvio** [comment]
Recebi resposta. O usuário padrão (ECT / SRO) não retorna os detalhes mais. Precisa usar o usuário do contrato pra resolver isso. :(

**Comment by iurisilvio** [comment]
Para quem tem contrato com os Correios, adicionei a opção de passar eles pelos headers `X-Correios-usuario` e `X-Correios-senha`. Essa senha não é gravada em nenhum lugar, mas usem HTTPS.

Quero fazer isso melhor, por meio de uma api key no Postmon para manter o usuário/senha de forma mais segura.

Eu não tenho contrato com Correios, preciso de alguém para validar o funcionamento.

**Comment by ricardofanetto** [comment]
Boa tarde, tem alguma ideia do custo para o contrato com o correio? será que é possível ratear isso?

**Comment by iurisilvio** [comment]
@ricardofanetto não tenho ideia. Nunca tive esse contrato. Se alguém tiver essa informação, posso considerar levar a ideia pra frente.

**Comment by iurisilvio** [comment]
Fazendo uma pesquisa rápida, encontrei esse link. http://ecommercenapratica.com/loja-virtual-contrato-correios/

```
Atualmente os valores mínimos são:

R$ 200 em envios por Pac,
R$ 200 em envios por Sedex,
R$ 1.700 em envios por ECOMMERCE1 (substituto E-sedex).
```

Não sei se tem algum contrato mais simples, mas isso aí é inviável para o Postmon.

**Comment by iurisilvio** [comment]
Estou testando uma solução alternativa, por enquanto está funcionando. Ainda não sei se vai ser bloqueado por IP.

**Comment by peteraf** [comment]
Bacana , esta funcionando bem.
