### ISSUE TITLE
CEP 58800732 Erro 404

### ISSUE THREAD

**Issue by mrharbas** [PostmonAPI/postmon#176]
O CEP 58800732 existe nos correios, mas retorna 404 no postmon.

![cep encontrado](https://user-images.githubusercontent.com/32140077/30657237-3e5121c4-9e0d-11e7-8e2f-e21722f06943.png)

**Comment by rafaelgontijo** [comment]
Esse erro foi resolvido, da uma olha.

**Comment by iurisilvio** [comment]
Corrigido com o #177. Tkz @rafaelgontijo
