### ISSUE TITLE
Erro 502 - CEP 50030970

### ISSUE THREAD

**Issue by mrharbas** [PostmonAPI/postmon#178]
Quando consulto o CEP 50030970

com a URL http://api.postmon.com.br/v1/cep/50030970

retorna erro 502

veja tela em anexo. Já consultei nos correios e o cep existe e está ok.
![erro](https://user-images.githubusercontent.com/32140077/31742375-23b83ffc-b436-11e7-8d9e-2c6b60e86dd8.png)

**Comment by iurisilvio** [comment]
É um erro com os CEPs `*9xx`. Tem que ser tratado.

**Comment by iurisilvio** [comment]
Problema tratado, já em produção.
