### ISSUE TITLE
alguns ceps retornando com caracteres especiais

### ISSUE THREAD

**Issue by webesistemas** [PostmonAPI/postmon#179]
exemplo 

63110-080
12505-506  Chï¿½cara Selles

**Comment by rodrigopires** [comment]
Mesmo problema aqui...

http://api.postmon.com.br/v1/cep/13173331

Retorna: cidade: "Sumarï¿½",

Alguma solução para o problema?

**Comment by welintonInfo** [comment]
Também estou com esse problema? 
Nenhuma solução ao que parece.

**Comment by ivanaugustobd** [comment]
Removendo o `-` do CEP resolveu aqui..

[35501318](http://api.postmon.com.br/v1/cep/35501318) // tudo ok
[35501-318](http://api.postmon.com.br/v1/cep/35501-318) // caracteres "ï¿½"

**Comment by rodrigopires** [comment]
@ivanaugustobd no meu exemplo está sem hífen... e mesmo assim o problema acontece:

http://api.postmon.com.br/v1/cep/13173331

**Comment by thiagoluis** [comment]
Também estou com o mesmo problema:

```
curl http://api.postmon.com.br/v1/cep/75072160
{"bairro": "Jardim dos Ip\u00ef\u00bf\u00bds", "cidade": "An\u00ef\u00bf\u00bdpolis", ...}
```

"cidade": "An\u00ef\u00bf\u00bdpolis", 
A cidade acima é Anápolis.

Retorna assim:
ï = **\u00ef**  - https://unicode-table.com/pt/#00EF

Deveria ser:
á = **\u00e1** - https://unicode-table.com/pt/#00E1

**Comment by jhullse** [comment]
+1

**Comment by fosantana** [comment]
Também estou com esse problema.
http://api.postmon.com.br/v1/cep/32672346
**Como deveria retornar o bairro:** Senhora de Fátima
**Retorno:** "Senhora de F\u00ef\u00bf\u00bdtima

**Comment by CesarBellon** [comment]
Também estou, no nome do bairro
https://api.postmon.com.br/v1/cep/85804400
Deveria retornar: Guarujá

**Comment by iurisilvio** [comment]
Vi isso em produção, mas ainda não consegui reproduzir local. :/

**Comment by jhullse** [comment]
@iurisilvio testando com o CEP 86082-105

```
{
    "bairro": "Jardim Paris",
    "cep": "86082105",
    "cidade": "Londrina",
    "cidade_info": {
        "area_km2": "1652,569",
        "codigo_ibge": "4113700"
    },
    "estado": "PR",
    "estado_info": {
        "area_km2": "199.307,985",
        "codigo_ibge": "41",
        "nome": "Paraná"
    },
    "logradouro": "Rua Lï¿½zaro Brandino da Silva"
}
```

da pra perceber que o estado, Paraná, está retornando corretamente porém o logradouro não, imaginei que pudesse ser algum problema de encoding de alguma tabela ou coluna específica. Seria isso possível? Talvez as configurações de encoding local estejam diferentes da de produção.

**Comment by iurisilvio** [comment]
A fonte do `estado_info` é outra. O `logradouro` vem do site dos Correios, o `estado_info` do IBGE. Alguma coisa mudou no site dos Correios que quebrou o encoding. Vou tentar resolver isso hoje.

**Comment by iurisilvio** [comment]
A informação está salva errada no mongo, então o problema é no scraper mesmo.

**Comment by mgonzagajr** [comment]
Alguma novidade? Estou com o mesmo problema.

**Comment by iurisilvio** [comment]
Resolvi o bug, limpei o cache.

Foi difícil de entender porque só em produção que estava usando um proxy para rotação de IP.

Preciso de uma solução de proxy melhor.

**Comment by CesarBellon** [comment]
Ainda está vindo os endereços com erro
