### ISSUE TITLE
Cep 30530036 vem com logradouro com caracteres nao identificados

### ISSUE THREAD

**Issue by pedroBraga3003** [PostmonAPI/postmon#182]
30530036 -
Resultado do SITE :
{"bairro":"Delta","cidade":"Belo Horizonte","logradouro":"Beco Zï¿½ do Chapï¿½u","estado_info":{"area_km2":"586.521,235","codigo_ibge":"31","nome":"Minas Gerais"},"cep":"30530036","cidade_info":{"area_km2":"331,401","codigo_ibge":"3106200"},"estado":"MG"}

**Comment by iurisilvio** [comment]
Resolvido. Explicações no #179.
