### ISSUE TITLE
CEP 25650-026 retorna caracteres inválidos.

### ISSUE THREAD

**Issue by chrisalves** [PostmonAPI/postmon#183]
O CEP 25650-026 retorna caracteres inválidos ao tratar acentos. 
{"complemento":"atï¿½ 382 - lado par","bairro":"Quitandinha","cidade":"Petrï¿½polis","logradouro":"Rua General Rondon","estado_info":{"area_km2":"43.781,566","codigo_ibge":"33","nome":"Rio de Janeiro"},"cep":"25650026","estado":"RJ"}
Erros: Indicação de número (até...), Nome da Cidade (Petrópolis).

Este CEP é de Petrópolis, RJ. Outros CEPs de Petrópolis retornam o nome da cidade corretamente. Exemplo de um CEP que funciona corretamente é 25655-007

**Comment by chrisalves** [comment]
Retorno do API.
http://api.postmon.com.br//v1/cep/25650026


{"complemento": "at\u00ef\u00bf\u00bd 382 - lado par", "bairro": "Quitandinha", "cidade": "Petr\u00ef\u00bf\u00bdpolis", "logradouro": "Rua General Rondon", "estado_info": {"area_km2": "43.781,566", "codigo_ibge": "33", "nome": "Rio de Janeiro"}, "cep": "25650026", "estado": "RJ"}

**Comment by MarceloABastos** [comment]
CEP 08490-000 e 12216-710 retornando as cidades com caracteres especiais.

**Comment by Maethorin** [comment]
Acredito que isso tenha sido causado por alguma atualização de base de dados, pq não estava assim antes. Agora, vários CEPs testados estão com esse encoding diferente que o browser não entende.

**Comment by iurisilvio** [comment]
Resolvido. Explicações no #179.

**Comment by chrisalves** [comment]
Perfeito! Resolvido! Agradeço!!!
:-)
