### ISSUE TITLE
CEP 06882110 com erro de codificação

### ISSUE THREAD

**Issue by phrbarbosa** [PostmonAPI/postmon#184]
Amigos, vejam o retorno do webservice para o cep em questão:

{"bairro":"Potuverï¿½","cidade":"Itapecerica da Serra","logradouro":"Rua Sebastiï¿½o Pereira da Silva","estado_info":{"area_km2":"248.221,996","codigo_ibge":"35","nome":"São Paulo"},"cep":"06882110","cidade_info":{"area_km2":"150,742","codigo_ibge":"3522208"},"estado":"SP"}

O nome do bairro e do logradouro estão com problema de codificação.

**Comment by iurisilvio** [comment]
Resolvido. Explicações no #179.
