### ISSUE TITLE
CEP com caracteres inválidos.

### ISSUE THREAD

**Issue by DaviAragao** [PostmonAPI/postmon#188]
A resposta da API coloca caracteres inválidos no objeto na hora da conversão.

```
{bairro: "Vila Brasil", cidade: "Tatuï¿½", logradouro: "Rua Eduardo Bastos",…}
```

**Comment by iurisilvio** [comment]
Resolvido. Explicações no #179.

**Comment by CesarBellon** [comment]
Não está resolvido. Ainda está vindo com erro
https://api.postmon.com.br/v1/cep/85804400

**Comment by iurisilvio** [comment]
Na verdade voltei para o problema anterior, que é de ser bloqueado pelo IP. :/

**Comment by CesarBellon** [comment]
Sim. Agr não estou nem conseguindo acessar a página :(

**Comment by iurisilvio** [comment]
Estabilizado com um proxy diferente.

A performance piorou, mas pelo menos agora responde. Vou ainda pesquisar soluções melhores.

**Comment by CesarBellon** [comment]
Continua vindo com erro o endereço
{"bairro": "Guaruj\u00e1", "cidade": "Cascavel", "logradouro": "Rua das Violetas", "estado_info": {"area_km2": "199.307,985", "codigo_ibge": "41", "nome": "Paran\u00e1"}, "cep": "85804400", "cidade_info": {"area_km2": "2100,831", "codigo_ibge": "4104808"}, "estado": "PR"}

**Comment by iurisilvio** [comment]
Essa é a codificação UTF-8 normal de um JSON. Cole esse resultado por
exemplo no https://jsoneditoronline.org/ para validar.
