### ISSUE TITLE
CEPs sem retorno na API

### ISSUE THREAD

**Issue by Ericwerise** [PostmonAPI/postmon#189]
09015-007

**Comment by cewitte** [comment]
{"readyState":0,"responseText":"","status":0,"statusText":"error"}

**Comment by Connectuse** [comment]
Mesmo problema para todos os CEP's que tento consultar.

**Comment by iurisilvio** [comment]
Retornando normal. Hoje fiz uma mudança grande no funcionamento dos proxies do Postmon, teve instabilidade.

Resolvido. Explicações no #179.
