### ISSUE TITLE
404 em CEP válido

### ISSUE THREAD

**Issue by efreesen** [PostmonAPI/postmon#197]
Ao fazer uma consulta pelo CEP 39400-000 através da URL:

http://api.postmon.com.br/v1/cep/39400000

Recebo 404, com o cep 39400-001 funciona normalmente.

**Comment by iurisilvio** [comment]
O CEP foi alterado pelos Correios.

```
ATENÇÃO! O CEP 39400-000 FOI ALTERADO CONFORME ABAIXO.

Logradouro/Nome: | Bairro/Distrito: | Localidade/UF: | CEP:
-- | -- | -- | --
Praça Doutor Carlos Versiani | Centro | Montes Claros/MG | 39400-612
```

**Comment by efreesen** [comment]
Entendi, obrigado pelo esclarecimento.

Talvez fosse interessante dar um retorno diferente nesses casos ao invés de retornar um `404`.

**Comment by andrekutianski** [comment]
Seria possível tratar o retorno quando há uma alteração do cep para apresentar o novo endereço fornecido pelos Correios?
