### ISSUE TITLE
Dúvida: como são conectadas localidades inconsistentes entre a API dos correios e dados do IBGE?

### ISSUE THREAD

**Issue by varnion** [PostmonAPI/postmon#200]
Estou pensando em deixar de usar o ViaCEP para usar (e possivelmente contribuir) com o postmon, pois preciso usar o código do municipio no IBGE para lidar com algumas inconsistencias entre a api dos correios e a do IBGE. Acho que é um tipo de inconsistencia que o Postmon trata, mas ainda não encontrei o código.

Exemplo: notei que no MT existe uma cidade nova chamada "Boa Esperança", que era parte de Sorriso. Para o IBGE essa cidade não existe. Porém, para os Correios, ela existe e se chama "Boa Esperança (Sorriso)". Busquei o CEP dessa localidade na API do postmon e ela retornou "Boa Esperança (Sorriso)" e o código correto do IBGE (o de Sorriso).

**Comment by iurisilvio** [comment]
É um match complexo, mas acho que acertamos todas as cidades. Limpa acentos, considera o nome da cidade ou o nome entre parenteses. Tem mais alguns detalhes. O código pode ser visto aqui: https://github.com/PostmonAPI/postmon/blob/master/database.py#L46
