### ISSUE TITLE
Ambiente fora

### ISSUE THREAD

**Issue by leonardoaa** [PostmonAPI/postmon#204]
Pessoal, a consulta esta retornando a msg:

Error 504 Ray ID: 3fb0277610aa4a24 • 2018-03-13 17:18:27 UTC
Gateway time-out

**Comment by mitanix79** [comment]
Também estou com problemas.. até a consulta no site de vocês estão dando erro.

**Comment by rhiroyuki** [comment]
Também estamos passando pela mesma situação.

**Comment by MarceloABastos** [comment]
Prezados,
Também estou passando pela mesma situação.
Nenhum endereço está retornando na consulta.
No aguardo da solução.
Grato.

**Comment by iurisilvio** [comment]
A queda foi em função da queda dos Correios que gerou uma queue que derrubou o serviço do Postmon.

https://status.postmon.com.br/
