### ISSUE TITLE
Ambiente fora do ar

### ISSUE THREAD

**Issue by MarceloABastos** [PostmonAPI/postmon#208]
Prezados,
Estamos com problemas no retorno dos endereços pela API.
Poderiam verificar o problema por favor.
Grato,
Marcelo Bastos

**Comment by ioferreira** [comment]
Funcionando perfeitamente. Digite um domínio em h0s1.net e depois um CEP.

[cid:image003.png@01D3BAF7.86562F80]

Igor Oliveira Ferreira
igor.ferreira.nom.br
(21) 97641-4530

"Ele também veio para, das ilusões, curar a humanidade." (19/10/2017)

________________________________
De: MarceloABastos <notifications@github.com>
Enviado: Tuesday, March 13, 2018 5:04:36 PM
Para: PostmonAPI/postmon
Cc: Subscribed
Assunto: [PostmonAPI/postmon] Ambiente fora do ar (#208)


Prezados,
Estamos com problemas no retorno dos endereços pela API.
Poderiam verificar o problema por favor.
Grato,
Marcelo Bastos

**Comment by iurisilvio** [comment]
Ficou algum tempo fora, mas já está de volta.

**Comment by iurisilvio** [comment]
Ver #204.
