### ISSUE TITLE
Erro 503 ao consultar um cep em específico: 93542-394

### ISSUE THREAD

**Issue by danielbohnrs** [PostmonAPI/postmon#209]
Olá,
alguém se deparou com algum problema semelhante?
O cep em questão (93542-394) é o único (de todos que testei aqui) que está dando este retorno:
{"readyState":4,"responseText":"","status":503,"statusText":"Servico Temporariamente Indisponivel"}

Os demais está retornando os dados normalmente.
Alguma dica?

**Comment by caesarpanda** [comment]
@danielbohnrs ontem e hj estou com o mesmo problema no CEP 03274-040 aqui de SP.

**Comment by gbelisario** [comment]
Mesma coisa para o CEP 16400-303

**Comment by aderbas** [comment]
Abandonaram esse projeto? Ninguém resolveu ainda isso do Error 503? Aparentemente está dando esse erro quando o cep não foi encontrado.

**Comment by iurisilvio** [comment]
Resolvido.

http://api.postmon.com.br/v1/cep/93542-394
http://api.postmon.com.br/v1/cep/03274-040
http://api.postmon.com.br/v1/cep/16400-303
