### ISSUE TITLE
Erro ao consultar o CEP 29145-587

### ISSUE THREAD

**Issue by MarceloABastos** [PostmonAPI/postmon#210]
Prezados,
Ao consultar o CEP 29145-587, aparece a mensagem abaixo:
{"readyState":4,"responseText":"","status":503,"statusText":"Servico Temporariamente Indisponivel"}

Favor avaliar,
No aguardo.

**Comment by iurisilvio** [comment]
O CEP não existe na base dos Correios. Era um erro estar retornando 503. Agora está retornando 404 conforme esperado.
