### ISSUE TITLE
Não esta consultando o CEP 85903756

### ISSUE THREAD

**Issue by cristianoprause** [PostmonAPI/postmon#211]
Bom dia,

Ao consultar pelo CEP 85903756 esta retornando um JSON vazio, buscando pela URL http://api.postmon.com.br/v1/cep/85903756 no navegador ele retorna uma página vazia.
O CEP em questão é um CEP válido.

Estou no aguardo,

**Comment by iurisilvio** [comment]
Resolvido. http://api.postmon.com.br/v1/cep/85903756

**Comment by cristianoprause** [comment]
Muito obrigado
