### ISSUE TITLE
Servico Temporariamente Indisponivel

### ISSUE THREAD

**Issue by RobertoBarros** [PostmonAPI/postmon#212]
Aparentemente alguns CEPs não estão sendo carregados, como por exemplo 81200-020

Ao consultar o CEP a API retorna:
```
{"readyState":4,"responseText":"","status":503,"statusText":"Servico Temporariamente Indisponivel"}
```

**Comment by iurisilvio** [comment]
Resolvido. http://api.postmon.com.br/v1/cep/81200-020
