### ISSUE TITLE
CEP ERRO 503

### ISSUE THREAD

**Issue by MarcosArtigas** [PostmonAPI/postmon#214]
Ao realizar a consulta para o seguinte cep:
**35041-750**
Retorna o seguinte erro:
{"readyState":4,"responseText":"","status":503,"statusText":"Service Unavailable"}

Se consultar no site dos correios, o cep é valido.

Logradouro/Nome: | Bairro/Distrito: | Localidade/UF: | CEP:
Rua Vasco da Gama | Vera Cruz | Governador Valadares/MG | 35041-750

**Comment by iurisilvio** [comment]
Resolvido. http://api.postmon.com.br/v1/cep/35041-750
