### ISSUE TITLE
Erro para alguns CEPs

### ISSUE THREAD

**Issue by anaelisasiena** [PostmonAPI/postmon#217]
Boa tarde,

Alguns CEPs válidos estão dando erro. Poderiam verificar o motivo deles estarem indisponíveis, por favor? Como estas aqui: 41230-440.

![image](https://user-images.githubusercontent.com/38736523/39269933-ba60e5cc-48aa-11e8-9f33-0fc07c1e664d.png)

Agradeço desde já!

Abraços!

**Comment by iurisilvio** [comment]
Resolvido. http://api.postmon.com.br/v1/cep/41230-440
