### ISSUE TITLE
[Docker] Container morre após o start

### ISSUE THREAD

**Issue by vandalvnl** [PostmonAPI/postmon#220]
Recentemente, para fazer o uso local do servidor postmon, resolvi subir a aplicação em um container Docker para testes. Infelizmente, não obtive sucesso no uso, apresentando uns erros que não consegui identificar a origem. 

Como é a primeira vez do uso em container, não sei se é um erro relacionado ao último commit da branch master ou algum outro erro

[Link do Gist com o erro](https://gist.github.com/vandalvnl/2a19b98566ac2cf1dc6add9c3fed9f03)

**Comment by iurisilvio** [comment]
Isso é o pacote `six` desatualizado. Não sei exatamente quem está forçando essa versão antiga, tem que entender as dependências.

**Comment by horstmannmat** [comment]
Acho que essa issue pode ser fechada, O Dockerfile sofreu atualizaçoes, e não  morre mais :)

**Comment by iurisilvio** [comment]
:+1:
