### ISSUE TITLE
CEP  01513-010/95180000 RETORNANDO ERRO NA CONSULTA

### ISSUE THREAD

**Issue by Connectuse** [PostmonAPI/postmon#221]
01513-010
{"readyState":0,"responseText":"","status":0,"statusText":"error"}
Rua Doutor Tomaz de Lima | Liberdade

95180-000
{"readyState":0,"responseText":"","status":0,"statusText":"error"}
Farroupilha - RS

**Comment by iurisilvio** [comment]
O CEP 01513-010 está ok.

O CEP 95180-000 não existe na consulta dos Correios.
