### ISSUE TITLE
CEP 13184-752 não encontrado

### ISSUE THREAD

**Issue by hugogrochau** [PostmonAPI/postmon#222]
O serviço do postmon é excelente. Tivemos somente esse problema até agora:

O CEP 13184-752 não é encontrado no serviço ( https://api.postmon.com.br/v1/cep/13184752 ), mas consta na base do correios. 

O que pode estar causando isso? É um CEP muito novo que ainda não foi refletido na base?

**Comment by iurisilvio** [comment]
Resolvido.

https://api.postmon.com.br/v1/cep/13184752

Ele tinha sido marcado como não encontrado.
