### ISSUE TITLE
Ratreamento de objetos retornando error 404

### ISSUE THREAD

**Issue by danilobbezerra** [PostmonAPI/postmon#223]
Estou tentando rastrear o objeto: PM372097188BR e está retornando erro 404.

https://api.postmon.com.br/v1/rastreio/ect/PM372097188BR

O que pode ser?

**Comment by iurisilvio** [comment]
Provavelmente ainda não estava cadastrado nos Correios.

**Comment by danilobbezerra** [comment]
Estava sim, ficou dias nos correios mudando status mas na api não mudava.

**Comment by iurisilvio** [comment]
Analisando melhor descobri que tem um cache que deve ter sido responsável por isso. O #225 é o mesmo problema, então não vou reabrir essa.
