### ISSUE TITLE
Dados de rastreamento não estão atualizados

### ISSUE THREAD

**Issue by Farjax** [PostmonAPI/postmon#225]
Há alguns códigos de rastreamento que há algum tempo não são atualizados pela API.
Ex:  http://api.postmon.com.br/v1/rastreio/ect/DY948852112BR

Esta encomenda já foi entregue e no site do correios está com essa informação há vários dias(23/07). Só que na API , hoje, só exibe informações de rastreio até dia 19/07.

**Comment by iurisilvio** [comment]
Tem um cache errado que está segurando o `/rastreio` mais do que deveria. Vou ajustar isso.

**Comment by iurisilvio** [comment]
Faz alguns dias que reduzi o cache do `/v1/rastreio/`. Fechando a issue, me avise se o problema persistir.
