### ISSUE TITLE
Consulta à API online retornando OPTIONS com 405 Method Not Allowed

### ISSUE THREAD

**Issue by DfKimera** [PostmonAPI/postmon#226]
Ao tentar rodar um request usando o Axios, o Chrome barra a solicitação devido a um erro de CORS:

![image](https://user-images.githubusercontent.com/581765/44286748-9539cd00-a240-11e8-8ef6-afaef0a6424f.png)

![image](https://user-images.githubusercontent.com/581765/44286702-63c10180-a240-11e8-824a-e02f4fc42c01.png)

Aparentemente a API não está autorizando o request de pre-flight com o método OPTIONS.

**Comment by iurisilvio** [comment]
Corrigido parcialmente em produção, ainda vou fazer um commit com a solução definitiva.

**Comment by odapp** [comment]
O problema ainda está ocorrendo usando axios.

**Comment by odapp** [comment]
Resolvi o problema, era um header incorreto na minha requisição, pode fechar a issue.
Obrigado!

**Comment by LeoCidral** [comment]
Estou tentando fazer a chamada para a api pelo Angular... porem esta dando esse erro:

Request Method: OPTIONS
405 (Method Not Allowed)

Teria como implementar esse método para uso nessa tecnologia?

**Comment by ErickXavier** [comment]
> Resolvi o problema, era um header incorreto na minha requisição, pode fechar a issue.
> Obrigado!

pode especificar o header incorreto? :)

**Comment by odapp** [comment]
Não lembro qual era o header, verifique quais está enviando no request e
teste um de cada vez ou sem nenhum header.
