### ISSUE TITLE
Cache de retorno - Rastreio

### ISSUE THREAD

**Issue by danilobbezerra** [PostmonAPI/postmon#227]
Descobri que ao chamar a URL
[https://api.postmon.com.br/v1/rastreio/ect/PM319262616BR](https://api.postmon.com.br/v1/rastreio/ect/PM319262616BR)
o resultado sempre vem: 
`{"codigo": "PM319262616BR", "servico": "ect", "historico": [{"detalhes": "", "local": "SAO PAULO/SP", "data": "17/08/2018 14:07", "situacao": "Objeto postado"}]}`

Mas quando chamei a mesma URL colocando algo na querystring o resultado vem diferente:
[https://api.postmon.com.br/v1/rastreio/ect/PM319262616BR?teste=1](https://api.postmon.com.br/v1/rastreio/ect/PM319262616BR?teste=1)

`{"codigo": "PM319262616BR", "servico": "ect", "historico": [{"detalhes": "", "local": "SAO PAULO/SP", "data": "17/08/2018 14:07", "situacao": "Objeto postado"}, {"detalhes": "Objeto encaminhado de Ag\u00c3\u00aancia dos Correios em SAO PAULO / SP para Unidade de Tratamento em SAO PAULO / SP", "local": "SAO PAULO/SP", "data": "20/08/2018 10:36", "situacao": "Objeto encaminhado"}, {"detalhes": "Objeto encaminhado de Unidade de Tratamento em SAO PAULO / SP para Unidade de Tratamento em SAO PAULO / SP", "local": "SAO PAULO/SP", "data": "20/08/2018 23:09", "situacao": "Objeto encaminhado"}, {"detalhes": "Objeto encaminhado de Unidade de Tratamento em SAO PAULO / SP para Unidade de Distribui\u00e7\u00e3o em COTIA / SP", "local": "SAO PAULO/SP", "data": "21/08/2018 04:58", "situacao": "Objeto encaminhado"}, {"detalhes": "", "local": "COTIA/SP", "data": "21/08/2018 11:32", "situacao": "Objeto saiu para entrega ao destinat\u00c3\u00a1rio"}, {"detalhes": "", "local": "COTIA/SP", "data": "21/08/2018 17:44", "situacao": "A entrega n\u00e3o pode ser efetuada - Carteiro n\u00e3o atendido"}, {"detalhes": "", "local": "COTIA/SP", "data": "22/08/2018 10:31", "situacao": "Objeto saiu para entrega ao destinat\u00c3\u00a1rio"}, {"detalhes": "", "local": "COTIA/SP", "data": "22/08/2018 16:57", "situacao": "A entrega n\u00e3o pode ser efetuada - Carteiro n\u00e3o atendido"}]}`

**Comment by iurisilvio** [comment]
Tinha um cache muito longo (30d) no endpoint. Alterei faz uns dias, me avise se o problema persistir.

Relacionada com #225.
