### ISSUE TITLE
Endpoint do retorno das entregas não funciona

### ISSUE THREAD

**Issue by lokharth** [PostmonAPI/postmon#231]
A algumas semanas o endpoint que retorna o status dos pedidos parou de funcionar, tem alguma noticia do que aconteceu ?

**Comment by tcosta84** [comment]
Está dando erro 404  pra você também? Tem alguma novidade? Valeu!

**Comment by lokharth** [comment]
Sim, erro 404 o pessoal da responsável pelo projeto tem alguma noticia ?

**Comment by iurisilvio** [comment]
Corrigido. Os Correios realmente mudaram a interface. :cry: 

https://github.com/aleborba/packtrack/commit/30e790e1304a6265ffd2ecdcf21980e4619ef001

**Comment by iurisilvio** [comment]
Obrigado pelos reports, o GitHub que não é muito bom pra me avisar dessas issues.
