### ISSUE TITLE
CEP 15823000 não encontrado

### ISSUE THREAD

**Issue by mathxbap** [PostmonAPI/postmon#237]
Olá, o CEP 15823-000 não é encontrado.

Tendo em vista que ele corresponde a cidade Elisário / SP
http://www.buscacep.correios.com.br/sistemas/buscacep/

Obrigado

**Comment by iurisilvio** [comment]
A Locaweb sofreu umas instabilidades, deve ter sido por isso.

https://statusblog.locaweb.com.br/category/hospedagem

O CEP está ok http://api.postmon.com.br/v1/cep/15823-000
