### ISSUE TITLE
API não está retornando CEPs

### ISSUE THREAD

**Issue by rnunesgarcia** [PostmonAPI/postmon#238]
Bom dia,
Estamos notando que desde manhã não está retornando cep.  Mesmo diretamente pelo site do postmon, está retornando Error 504.
Curiosamente alguns ceps estão funcionando, como 18120000. Outros(a maioria) ficam  carregando por um longo período, e retornam erro no final.

Abraços.

**Comment by sandsu** [comment]
Também estou enfrentando esse problema, o tempo de respota da api aumento consideravelmente desde ontem, chegando a quase 40 segundos eventualmente.

**Comment by fredericogg** [comment]
Mesmo problema!

**Comment by fredericogg** [comment]
Migrei para esta API aqui: https://viacep.com.br/ tem os mesmos recursos e parece ser mais estável.

**Comment by jeffotoni** [comment]
Mesmo problema para vários CEPS um deles é 31110590, cai direto no CLOUDFLARE.

**Comment by marcodpt** [comment]
Estou também enfrentando esse problema!

**Comment by marcodpt** [comment]
Aparentemente normalizou! Obrigado

**Comment by jeffotoni** [comment]
Sim, agora sim voltou...
Atualizações no CloudFlare depois de tudo prontinho é osso.

Valeu galera.

**Comment by rnunesgarcia** [comment]
Está normalizado desde ontem!!

Valeu Pessoal!!!
