### ISSUE TITLE
Sistema fora do ar

### ISSUE THREAD

**Issue by franzvsramos** [PostmonAPI/postmon#239]
Boa tarde!

Existe algum método que retorne se o serviço está indisponível? Meus clientes estão recebendo a mesma mensagem para CEP não encontrado tanto quando o serviço sai do ar, quando ele não encontra de fato um CEP. Isso está gerando atendimento. Gostaria de saber se tem uma forma de diferenciar essas duas situações.

**Comment by iurisilvio** [comment]
Você pode conferir a status message. Por exemplo, se o CEP não existe, retorna `404 CEP 12345000 nao encontrado`. https://github.com/PostmonAPI/postmon/blob/212e2d8d72aefa810e098a7bad442442e0f9fcf5/PostmonServer.py#L151

Além disso, você pode monitorar o endpoint de healthcheck. Não tem nenhum cache nesse endpoint. https://api.postmon.com.br/__health__

Se algum serviço externo não responde, o postmon vai responder com algum `50x`. O caso mais difícil é quando o sistema dos correios não falha, só retorna vazio (acontece ocasionalmente).

Além disso, tem a página pública do uptimerobot. https://status.postmon.com.br/ Dá pra pegar os dados diretamente por JSON https://status.postmon.com.br/api/status-page/M8rw6S5mP/1?sort=1
