### ISSUE TITLE
Água Boa é no MS e não no MT

### ISSUE THREAD

**Issue by LucasKuhn** [PostmonAPI/postmon#241]
Buscando o cep 78635000 diz que é em MT, mas é em MS:
https://cidades.ibge.gov.br/brasil/mt/agua-boa/

**Comment by horstmannmat** [comment]
A consulta nos [correios](http://www.buscacep.correios.com.br/sistemas/buscacep/BuscaCepEndereco.cfm) retorna que o CEP 78635000 está no MT, portanto a aplicação está de consistente com o banco de dados da instituição correios.

Deve haver formas de reportar o erro a instituição.

**Comment by iurisilvio** [comment]
Como já disse o @horstmannmat, é o que os Correios retornam, não temos como tratar.
