### ISSUE TITLE
CEP 65058107 Não Encontrado

### ISSUE THREAD

**Issue by Connectuse** [PostmonAPI/postmon#242]
Boa tarde, o CEP 65058-107 não está sendo localizado. De acordo com os Correios é o seguinte endereço: Rua 12 (Unidade 103), Cidade Operária, São Luís - MA.

**Comment by horstmannmat** [comment]
@iurisilvio, eu testei na [instancia](http://postmon.c3sl.ufpr.br/v1/cep/65058-107) do @c3sl e o retorno foi o esperado, porém na [instancia](https://api.postmon.com.br/v1/cep/65058-107) do postmon não, talvez tenha feito o acesso quando os correios estavam off, ou algum bug. :(

**Comment by iurisilvio** [comment]
Testei agora e foi normalmente. Corrigido.
