### ISSUE TITLE
API fora do ar!

### ISSUE THREAD

**Issue by rickdroio** [PostmonAPI/postmon#244]
API está do fora do ar já por algumas horas de hoje (01/05/2019)

**Comment by iurisilvio** [comment]
Últimos dias foram complicados por aumento de carga e limitações de servidor. Estou migrando para máquinas maiores, mas também adicionei umas proteções para isso não acontecer de novo.

Além disso, devo criar um cluster adicional nos EUA, que é mais barato e boa parte dos requests pesados vem de lá (batch de servidores).
