### ISSUE TITLE
API parou de retornar codigos dos estados e cidades

### ISSUE THREAD

**Issue by marcodpt** [PostmonAPI/postmon#248]
Eu utilizo há alguns anos a API em produção!
Sou muito grato pelo excelente trabalho!
Porém eu dependo dos códigos das cidades e estados para o funcionamento do meu software devido a NFe.
O JSON sempre retornou esses valores. Porém aparentemente hoje o layout do JSON foi modificado.

**Comment by iurisilvio** [comment]
Tivemos um problema sério com nosso servidor, ficou faltando restaurar esses dados ou ligar o cronograma pra reprocessar. :/ Amanhã corrigirei isso. https://twitter.com/iurisilvio/status/1150823051786891264

**Comment by ayrtonvwf** [comment]
Como está o processo de restauração? Algo em que podemos ajudar?

**Comment by iurisilvio** [comment]
Obrigado por me lembrar. :+1: 

Fiz o restore agora pela manhã, limpei os caches todos e já deve estar ok.

Exemplo: https://api.postmon.com.br/v1/cep/01301100

Me avise se tiver algum outro problema relacionado.

**Comment by thiagolinsx** [comment]
Boa tarde meu amigo, verifiquei agora e ainda não está retornando o código do IBGE.

**Comment by thiagolinsx** [comment]
Tenho um pouco de urgência nisso, você pode me orientar para que te ajude a fazer esse ajuste?

**Comment by iurisilvio** [comment]
Resolvido novamente. Quando fechei tinha sido resolvido, mas fiz uma segunda migração e cometi o mesmo erro na migração de dados. :/

Agora o Postmon está em um bare metal grande, o que deve fazer ele ficar mais estável e suportar o aumento de carga.
