### ISSUE TITLE
Precisa atualizar os CEPs da cidade de Indaiatuba SP

### ISSUE THREAD

**Issue by bruno-delfim** [PostmonAPI/postmon#255]
Tem vários CEPs da cidade de  Indaiatuba SP que retornam como não encontrados.
Acredito que precise atualizar a base de dados.
Segue alguns CEPs que deram erro:
13330-060
13330-135
13330-240

e muitos outros...

**Comment by RodriAndreotti** [comment]
Aparentemente aconteceu alguma coisa com o banco de dados deles, está dando problema com vários ceps, que antes funcionavam corretamente e agora pararam de funcionar, se observar, tem uns 4 ou 5 issues falando sobre isso já.

**Comment by iurisilvio** [comment]
Estou retomando o postmon, começando por limpar as issues.

Esses CEPs estão funcionando, obrigado pelo report e desculpas por demorar quase um ano pra ter uma resposta. :cry:

**Comment by RodriAndreotti** [comment]
> 
> 
> Estou retomando o postmon, começando por limpar as issues.
> 
> Esses CEPs estão funcionando, obrigado pelo report e desculpas por demorar quase um ano pra ter uma resposta. 😢

Acontece, entendemos, e obrigado pelo trabalho na API ;-)
