### ISSUE TITLE
Erro 503

### ISSUE THREAD

**Issue by diegocleir** [PostmonAPI/postmon#297]
Boa tarde ao Buscar alguns CEP, exemplo https://api.postmon.com.br/v1/cep/31555440, está apresentando. Poderia verificar?

**Comment by vitorvsv** [comment]
Parece ser todas as requests

**Comment by diegocleir** [comment]
Todos não. Só alguns ceps. Esse aqui funciona normalmente:
https://api.postmon.com.br/v1/cep/01010001

Em sex., 17 de nov. de 2023 11:47, Vítor Soares Vian <
***@***.***> escreveu:

**Comment by iurisilvio** [comment]
Corrigido com https://github.com/PostmonAPI/postmon/commit/548ff1c5086f9c5b7f9d27d5998cd84e6e8e7c2e. 🙏🏻

Reaproveitando a issue, mês passado falhou por outro motivo. O que não estava falhando agora, estava em cache.
