### ISSUE TITLE
Encoding incorreto na resposta do rastreamento

### ISSUE THREAD

**Issue by rpedigoni** [PostmonAPI/postmon#88]
Pessoal,
todas as chamadas de rastreamento devolvem acentos estranhos. Exemplo: http://api.postmon.com.br/v1/rastreio/ect/SF489654625BR

Tentei trocar o encoding no header da requisição mas não funcionou.

Exemplos:
```javascript
prуximo
destinatбrio
agкncia
```

Alguma dica?

**Comment by alcidesaraujo** [comment]
Gostaria de reabrir esse bug, estou sobrendo o mesmo problema.
Observem que no exemplo do colega: "Em tr\u0432nsito para CTCE BAURU - BAURU/SP"

\u0432 não é o caracter "â" (LATIN SMALL LETTER A WITH CIRCUMFLEX) e sim "в" (CYRILLIC SMALL LETTER VE) como pode ser visto aqui: http://www.fileformat.info/info/unicode/char/0432/index.htm

**Comment by iurisilvio** [comment]
Ok, então isso quer dizer que provavelmente tem alguma falha no parse do site dos Correios.

**Comment by alcidesaraujo** [comment]
iuri, você tem certeza? Pq na página dos Correios o HTML aparece correto aqui... "â". Você pode me indicar em qual arquivo esse parser é feito para eu dar uma investigada?

**Comment by iurisilvio** [comment]
Sim, o erro é do nosso lado, não dos Correios.

O parse disso é feito pelo packtrack (https://github.com/aleborba/packtrack). Provavelmente está faltando um decode dos dados.

Não tive tempo de analisar o problema, mas acredito que seja isso.

Qualquer contribuição é bem vinda, tanto aqui quanto no packtrack. :)

**Comment by iurisilvio** [comment]
Testei o packtrack aqui e ele já carrega informações erradas.

` u'Em tr\u0432nsito para CTCE RIBEIRAO PRETO - Ribeirao Preto/SP'`

**Comment by iurisilvio** [comment]
Tentei uma solução, mas não funcionou.

Tem algum encoding se perdendo no caminho. :/

**Comment by alcidesaraujo** [comment]
Parece que foi corrigido, veja esse exemplo: http://api.postmon.com.br/v1/rastreio/ect/DN685362260BR
"Em tr\u00e2nsito para CDD CARAGUATATUBA - Caraguatatuba/SP"
\u00e2 (LATIN SMALL LETTER A WITH CIRCUMFLEX) http://www.fileformat.info/info/unicode/char/00e2/index.htm

**Comment by iurisilvio** [comment]
:+1: 

Eu testei em um pacote que estava em cache. Por isso não vi que já estava certo.

A correção foi no packtrack. Fiz release dele e atualizei a versão da dependência no postmon.
https://github.com/aleborba/packtrack/commit/2c863b6096f599fa4191d0c1e5f6eaeca15d5119

**Comment by iurisilvio** [comment]
Obrigado @rpedigoni pelo report inicial e @alcidesaraujo por ajudar no mapeamento do problema.

**Comment by AlissonBertho** [comment]
Bom dia, estou tendo problemas semelhantes no uso dessa API. O cep http://api.postmon.com.br/v1/cep/84261360 está retornando:

bairro | "Centro"
-- | --
cidade | "Telï¿½maco Borba"
logradouro | "Rua Quatiguï¿½"
estado_info |  
area_km2 | "199.307,985"
codigo_ibge | "41"
nome | "Paraná"
cep | "84261360"
estado | "PR"

Algo pode ser feito para corrigir o encode?
